#!/bin/sh

if [ "$1" != "make" ]; then
    zephir fullclean
    zephir generate
    
    #remove gen trait
    rm -rf ext/yii/base/arrayaccesstrait.c
    rm -rf ext/yii/base/arrayaccesstrait.h
    rm -rf ext/yii/base/arrayabletrait.c
    rm -rf ext/yii/base/arrayabletrait.h   
    #copy trait
    cp -rf trait/base/* ext/yii/base/
    
    
    #remove file
    rm -rf ext/yii/helpers/arrayhelper.c
    rm -rf ext/yii/helpers/arrayhelper.h
    rm -rf /ext/yii/base/application.c
    rm -rf /ext/yii/base/application.h
    
    #copy fixed
    cp -rf fixed/helpers/* ext/yii/helpers/
    cp -rf fixed/base/* ext/yii/base/
fi

cd ext
phpize
./configure --with-php-config=php-config
make && sudo make install
cd ..
